apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: docker-registry
spec:
  serviceName: docker-registry-service
  replicas: 1

  selector:
    matchLabels:
      app: docker-registry

  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      volumes:
      - name: letsencrypt
        persistentVolumeClaim:
          claimName: certificate-pvc
          readOnly: true
      #      - name: docker-registry-data
      #        persistentVolumeClaim:
      #          claimName: docker-registry-pvc

      containers:
      - name: docker-registry
        image: registry
        resources:
          limits:
            memory: 64Mi
        ports:
        - containerPort: 5000
          name: registry-port
          hostPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: docker-registry-data
        - mountPath: /etc/letsencrypt
          name: letsencrypt
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /etc/letsencrypt/live/london.alexswilliams.co.uk/fullchain.pem
        - name: REGISTRY_HTTP_TLS_KEY
          value: /etc/letsencrypt/live/london.alexswilliams.co.uk/privkey.pem

  volumeClaimTemplates:
  - metadata:
      name: docker-registry-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi
