apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: registry-service
  replicas: 1

  selector:
    matchLabels:
      app: registry

  template:
    metadata:
      labels:
        app: registry
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: registry

      volumes:
      - name: letsencrypt
        persistentVolumeClaim:
          claimName: certificate-pvc
          readOnly: true
      - name: registry-htpasswd-volume
        secret:
          secretName: registry-htpasswd
          defaultMode: 0400

      containers:
      - name: registry
        image: registry:2.7.1
        resources:
          requests:
            memory: "8Mi"
            cpu: "4m"
          limits:
            memory: "48Mi"
            cpu: "10m"
        ports:
        - containerPort: 5000
          name: registry-port
          hostPort: 5000
        volumeMounts:
        - mountPath: /var/lib/registry
          name: registry-data
        - mountPath: /etc/letsencrypt
          name: letsencrypt
        - mountPath: /auth/htpasswd
          name: registry-htpasswd-volume
          subPath: htpasswd
          readOnly: true
        env:
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /etc/letsencrypt/live/london.alexswilliams.co.uk/fullchain.pem
        - name: REGISTRY_HTTP_TLS_KEY
          value: /etc/letsencrypt/live/london.alexswilliams.co.uk/privkey.pem
#        - name: REGISTRY_AUTH
#          value: htpasswd
#        - name: REGISTRY_AUTH_HTPASSWD_REALM
#          value: Registry Realm
#        - name: REGISTRY_AUTH_HTPASSWD_PATH
#          value: /auth/htpasswd
        - name: REGISTRY_LOG_LEVEL
          value: info
#        - name: REGISTRY_DELETE_ENABLED
#          value: true

  volumeClaimTemplates:
  - metadata:
      name: registry-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: local-storage
      resources:
        requests:
          storage: 1Gi
