# sudo docker run -it --rm --name certbot -p 80:80 -v "/mnt/k8s-pv/letsencrypt-pv:/var/lib/letsencrypt" -v "/mnt/k8s-pv/certificate-pv:/etc/letsencrypt" certbot/certbot certonly --standalone -d 'london.alexswilliams.co.uk'

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-renew-cronjob
spec:
  schedule: "34 3 * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet

          volumes:
            - name: etc
              persistentVolumeClaim:
                claimName: certificate-pvc

          containers:
            - name: letsencrypt-renew-job-container
              image: certbot/certbot:latest
              imagePullPolicy: Always
              args:
                - renew
                - --standalone
              ports:
                - containerPort: 80
                  hostPort: 80
              resources:
                requests:
                  memory: 64Mi
                limits:
                  memory: 64Mi

              volumeMounts:
                - mountPath: /etc/letsencrypt
                  name: etc
