apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: log-sync-s3-cronjob
spec:
  schedule: "56 2 * * *"
  startingDeadlineSeconds: 60
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          priorityClassName: backups
          automountServiceAccountToken: false

          volumes:
            - name: fluent-logs
              persistentVolumeClaim:
                claimName: fluent-pvc
            - name: aws-credentials
              secret:
                secretName: aws-fluent-credentials
                defaultMode: 0444
            - name: log-sync-s3-config
              configMap:
                name: log-sync-s3-config
                defaultMode: 0444

          containers:
            - name: log-sync-s3-job-container
              image: amazon/aws-cli:2.0.17
              env:
                - name: AWS_DEFAULT_REGION
                  value: eu-west-2
                - name: AWS_SHARED_CREDENTIALS_FILE
                  value: /credentials.json
              command:
                - sh
                - /entrypoint.sh
              resources:
                requests:
                  memory: "92Mi"
                  cpu: "20m"
                limits:
                  memory: "92Mi"
                  cpu: "20m"

              volumeMounts:
                - mountPath: /fluent-logs
                  name: fluent-logs
                - mountPath: /credentials.json
                  name: aws-credentials
                  subPath: credentials.json
                  readOnly: true
                - mountPath: /entrypoint.sh
                  name: log-sync-s3-config
                  subPath: entrypoint.sh
                  readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: log-sync-s3-config
data:
  entrypoint.sh: |
    #!/bin/sh

    cd /fluent-logs/all/
    aws s3 sync . s3://alexswilliams-co-uk-backups/fluentd/all/ --exclude="buffer.*" --storage-class=STANDARD_IA
