{
 "title": "Fluentd",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Output Log Lines per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_output_status_num_records_total[1m])) by (tag)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Received Lines per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(fluentd_input_status_num_records_total[1m])) by (tag)",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Output Buffer Queue Length",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_buffer_queue_length",
     "legendFormat": "{{type}} ({{plugin_id}})"
    }
   ]
  },
  {
   "title": "Bytes Written (minute average)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "increase(fluentd_output_status_buffer_total_bytes[1m])/60",
     "legendFormat": "{{type}} ({{plugin_id}})"
    }
   ]
  },
  {
   "title": "Errors Recorded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(fluentd_output_status_num_errors[1m])",
     "legendFormat": "{{type}} ({{plugin_id}})"
    }
   ]
  },
  {
   "title": "Retry",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "fluentd_output_status_retry_wait",
     "legendFormat": "Wait - {{type}} ({{plugin_id}})"
    },
    {
     "expr": "fluentd_output_status_retry_count",
     "legendFormat": "Count - {{type}} ({{plugin_id}})"
    }
   ]
  }
 ]
}