{
 "title": "Heater",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    { "expr": "power_mw", "legendFormat": "Power - {{alias}}" },
    { "expr": "state", "legendFormat": "State - {{alias}}" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    { "expr": "current_ma", "legendFormat": "Current - {{alias}}" },
    { "expr": "state", "legendFormat": "State - {{alias}}" }
   ]
  },
  {
   "title": "Total Power Consumed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(total_wh[$__range])"
    }
   ]
  },
  {
   "title": "Power State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "state" }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    { "expr": "voltage_mv", "legendFormat": "Voltage - {{alias}}" }
   ]
  },
  {
   "title": "Power Consumed in Window",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 13 },
   "format": "watth",
   "valueName": "diff",
   "targets": [
    { "expr": "total_wh" }
   ]
  },
  {
   "title": "Cost in Window",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 13 },
   "format": "currencyGBP",
   "valueName": "diff",
   "targets": [
    {
     "expr": "((total_wh * 14.3861) / 1000) / 100"
    }
   ]
  }
 ]
}