{
 "title": "Kube Node Status",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\",status=\"true\"}",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{kernel_version}}" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{os_image}}" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{kubelet_version}}" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "kube_node_info", "legendFormat": "{{kubeproxy_version}}" }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"PIDPressure\",status=\"true\"}",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"DiskPressure\",status=\"true\"}",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"NetworkUnavailable\",status=\"true\"}",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\",status=\"true\"}",
     "legendFormat": "Ready"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sort_desc(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node Memory Allocation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Node Allocation",
   "type": "bargauge",
   "gridPos": { "h": 18, "w": 5, "x": 19, "y": 4 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (node) / sum(kube_node_status_allocatable_memory_bytes) by (node)",
     "legendFormat": "Memory"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node) / sum(kube_node_status_allocatable_cpu_cores) by (node)",
     "legendFormat": "CPU"
    },
    {
     "expr": "count(kube_pod_container_resource_requests_cpu_cores) by (node) / sum(kube_node_status_allocatable_pods) by (node)",
     "legendFormat": "Pods"
    }
   ]
  },
  {
   "title": "Node CPU Allocation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (node) * 1000",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(kube_pod_container_resource_requests_cpu_cores)*1000",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node Pod Allocation",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kube_pod_container_resource_requests_cpu_cores) by (node)",
     "legendFormat": "Pods"
    }
   ]
  }
 ]
}