{
 "title": "Minecraft Client",
 "time": { "from": "now-2h", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Used",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed)"
    }
   ]
  },
  {
   "title": "Playtime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job='alex-minecraft-desktop'}",
     "legendFormat": "Time spent playing"
    }
   ]
  },
  { "title": "JVM Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Memory (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_max{area='heap'}",
     "legendFormat": "Heap"
    }
   ]
  },
  {
   "title": "Memory (Committed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_committed", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "Memory (Used)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}}" }
   ]
  },
  {
   "title": "Pool Memory (Max)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool!='Metaspace'}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Memory (Committed)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Memory (Used)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_pool_bytes_used", "legendFormat": "{{pool}}" }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "Classes Loaded" },
    {
     "expr": "increase(jvm_classes_loaded_total[1m])",
     "legendFormat": "Loads per minute"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_unloaded_total", "legendFormat": "Classes Unloaded" },
    {
     "expr": "increase(jvm_classes_unloaded_total[1m])",
     "legendFormat": "Unloads per minute"
    }
   ]
  },
  {
   "title": "GC Time per Minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum[1m]) * 1000",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current - jvm_threads_daemon",
       "legendFormat": "Interactive Threads"
      },
      { "expr": "jvm_threads_daemon", "legendFormat": "Daemon Threads" },
      {
       "expr": "increase(jvm_threads_started_total[1m])",
       "legendFormat": "New Threads per Minute"
      }
     ]
    }
   ]
  }
 ]
}