{
 "title": "Node Stats",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Time per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!='idle'}[1m])) by (instance, mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(node_procs_running)", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Load Averages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(node_load1)", "legendFormat": "Load Avg (1m)" },
    { "expr": "sum(node_load5)", "legendFormat": "Load Avg (5m)" },
    { "expr": "sum(node_load15)", "legendFormat": "Load Avg (15m)" }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Sockets In Use",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_sockstat_sockets_used)",
     "legendFormat": "Sockets"
    }
   ]
  },
  {
   "title": "Network Traffic (eth0)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes", "label": "Per Second Throughput" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total[1m])/60",
     "legendFormat": "In ({{device}})"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total[1m])/60",
     "legendFormat": "Out ({{device}})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes",
     "legendFormat": "Used"
    },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "Buffers" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free" }
   ]
  },
  {
   "title": "Paging and Swapping",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(node_vmstat_pgpgin[1m])", "legendFormat": "Page In" },
    { "expr": "irate(node_vmstat_pgpgout[1m])", "legendFormat": "Page Out" },
    { "expr": "irate(node_vmstat_pswpin[1m])", "legendFormat": "Swap In" },
    { "expr": "irate(node_vmstat_pswpout[1m])", "legendFormat": "Swap Out" }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapCached_bytes / node_memory_SwapTotal_bytes",
     "legendFormat": "Percentage Swap Usage"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(node_vmstat_pgfault[1m])", "legendFormat": "Page Faults" },
    {
     "expr": "irate(node_vmstat_pgmajfault[1m])",
     "legendFormat": "Major Page Faults"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Bytes Reads and Writes per Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes", "label": "Throughput per Minute" }
   ],
   "targets": [
    {
     "expr": "increase(node_disk_read_bytes_total[1m])",
     "legendFormat": "Read - {{device}}"
    },
    {
     "expr": "increase(node_disk_written_bytes_total[1m]) ",
     "legendFormat": "Write - {{device}}"
    }
   ]
  },
  {
   "title": "Free Space",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_filesystem_free_bytes", "legendFormat": "{{mountpoint}}" }
   ]
  },
  {
   "title": "File System Device Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "changes(node_filesystem_device_error[1m])",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Allocated File Descriptors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated / node_filefd_maximum",
     "legendFormat": "Percentage FDs Allocated"
    }
   ]
  }
 ]
}