{
 "title": "Power Sockets",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Socket",
    "query": "label_values(current_ma, alias)"
   }
  ]
 },
 "panels": [
  {
   "title": "Power Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "expr": "max(power_mw{alias=~\"$Socket\"}) by (alias)",
     "legendFormat": "Power - {{alias}}"
    },
    {
     "expr": "max(state{alias=~\"$Socket\"}) by (alias)",
     "legendFormat": "State - {{alias}}"
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "expr": "max(current_ma{alias=~\"$Socket\"}) by (alias)",
     "legendFormat": "Current - {{alias}}"
    },
    {
     "expr": "max(state{alias=~\"$Socket\"}) by (alias)",
     "legendFormat": "State - {{alias}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(state{alias=~\"$Socket\"})",
     "legendFormat": "Any Socket Powered"
    }
   ]
  },
  {
   "title": "Total Power in Window",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "format": "watth",
   "valueName": "diff",
   "targets": [
    {
     "expr": "sum(total_wh{alias=~\"$Socket\"})"
    }
   ]
  },
  {
   "title": "Supply Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "mvolt" }
   ],
   "targets": [
    {
     "expr": "max(voltage_mv{alias=~\"$Socket\"}) by (alias)",
     "legendFormat": "Voltage - {{alias}}"
    }
   ]
  }
 ]
}