{
 "title": "Router",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Hostname",
    "query": "label_values(snmp_ipInDelivers, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "VDSL - Download Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(interface_ifInOctets{ifDescr=\"VDSL\",hostname=\"$Hostname\"}[1m])",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "VDSL - Upload Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "irate(interface_ifOutOctets{ifDescr=\"VDSL\",hostname=\"$Hostname\"}[1m])",
     "legendFormat": "{{ifDescr}}"
    }
   ]
  },
  {
   "title": "VDSL Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Download Speed" }
   ],
   "targets": [
    {
     "expr": "irate(interface_ifInOctets{ifDescr=\"VDSL\",hostname=\"$Hostname\"}[1m])",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(interface_ifOutOctets{ifDescr=\"VDSL\",hostname=\"$Hostname\"}[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Download Line Speed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "snmp_adslAturCurrAttainableRate{hostname=\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "Upload Line Speed",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "expr": "snmp_adslAturChanCurrTxRate{hostname=\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "VDSL Transfer",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "Bps", "label": "Download Line Rate" }
   ],
   "targets": [
    {
     "expr": "snmp_adslAturCurrAttainableRate{hostname=\"$Hostname\"}",
     "legendFormat": "Download"
    },
    {
     "expr": "snmp_adslAturChanCurrTxRate{hostname=\"$Hostname\"}",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}