apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: fluent-log-volume
          persistentVolumeClaim:
            claimName: fluent-pvc

      initContainers:
        - name: prepare-node-for-fluent
          image: busybox
          command:
            - sh
            - -c
            - chmod -R 0777 /var/log/fluent
          volumeMounts:
            - name: fluent-log-volume
              mountPath: /var/log/fluent
          resources:
            requests:
              memory: 32Mi
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.4.2-debian-1.0
          resources:
            requests:
              memory: 42Mi
            limits:
              memory: 64Mi
          env:
            - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
              value: "0.9"
          ports:
            - containerPort: 5140
              protocol: UDP
              hostPort: 5140
              name: syslog-router
            - containerPort: 5141
              protocol: UDP
              hostPort: 5141
              name: syslog-ap

          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              name: fluentd-config
              subPath: fluent.conf
              readOnly: true
            - name: fluent-log-volume
              mountPath: /var/log/fluent/


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type syslog
      port 5140
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.router
    </source>
    <source>
      @type syslog
      port 5141
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.accesspoint
    </source>

    <filter syslog.draytek.**>
      @type record_transformer
      <record>
        logsource ${tag_parts[0]}
        category ${tag_parts[1]}
        devicetype ${tag_parts[2]}
      </record>
    </filter>

    <match **>
      @type file
      path /var/log/fluent/all/
      time_slice_format %Y%m%d
      compress gzip
      append true
      <buffer>
        timekey_use_utc
      </buffer>
    </match>
