apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config

      containers:
      - name: fluentd
        image: docker-registry-service:5000/fluentd-es:latest
        ports:
        - containerPort: 5140
          protocol: UDP
          hostPort: 5140
          name: syslog-router
        - containerPort: 5141
          protocol: UDP
          hostPort: 5141
          name: syslog-ap

        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: fluentd-config
          subPath: fluent.conf
          readOnly: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type syslog
      port 5140
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.router
    </source>
    <source>
      @type syslog
      port 5141
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.accesspoint
    </source>

    <filter syslog.draytek.**>
      @type record_transformer
      <record>
        system ${tag_parts[0]}
        subsystem ${tag_parts[1]}
        devicetype ${tag_parts[2]}
      </record>
    </filter>

    <filter **>
      @type record_transformer
      <record>
        time_received ${time}
        hostname ${hostname}
      </record>
    </filter>

    <match **>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      logstash_format true
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
