apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always

      # tolerations:
      #   - key: node-role.kubernetes.io/master
      #     effect: NoSchedule

      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config

      containers:
      - name: fluentd
        image: fluent/fluentd:stable
        ports:
        - containerPort: 9800
          protocol: TCP
          name: fluent-test
        - containerPort: 24224
          hostPort: 24224
          hostIP: 0.0.0.0
          protocol: TCP
          name: fluentd-tcp
        - containerPort: 24224
          hostPort: 24224
          hostIP: 0.0.0.0
          protocol: UDP
          name: fluentd-udp

        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: fluentd-config
          subPath: fluent.conf
          readOnly: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type http
      @id test_source
      port 9800
    </source>
    <match **>
      @type stdout
      @id console_out
    </match>
