apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: fluent-log-volume
          persistentVolumeClaim:
            claimName: fluent-pvc

      initContainers:
        - name: prepare-node-for-fluent
          image: busybox
          command:
            - sh
            - -c
            - chmod -R 0777 /var/log/fluent
          volumeMounts:
            - name: fluent-log-volume
              mountPath: /var/log/fluent
          resources:
            requests:
              memory: 32Mi
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.4.2-debian-1.0
          resources:
            requests:
              memory: 42Mi
              cpu: 20m
            limits:
              memory: 64Mi
              cpu: 50m
          env:
            - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
              value: "0.9"
          ports:
            - containerPort: 5140
              protocol: UDP
              hostPort: 5140
              name: syslog-router
            - containerPort: 5141
              protocol: UDP
              hostPort: 5141
              name: syslog-ap
            - containerPort: 24231
              name: metrics

          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              name: fluentd-config
              subPath: fluent.conf
              readOnly: true
            - name: fluent-log-volume
              mountPath: /var/log/fluent/


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type syslog
      port 5140
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.router
    </source>
    <source>
      @type syslog
      port 5141
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag syslog.draytek.accesspoint
    </source>

    <filter syslog.draytek.**>
      @type record_transformer
      <record>
        logsource ${tag_parts[0]}
        category ${tag_parts[1]}
        devicetype ${tag_parts[2]}
      </record>
    </filter>

    <match **>
      @type copy

      <store>
        @type file
        path /var/log/fluent/all/
        time_slice_format %Y%m%d
        compress gzip
        append true
        <buffer>
          timekey_use_utc
        </buffer>
      </store>

      <store ignore_error>
        # count number of outgoing records per tag
        @type prometheus
        <metric>
          name fluentd_output_status_num_records_total
          type counter
          desc The total number of outgoing records
          <labels>
            tag ${tag}
            hostname ${hostname}
          </labels>
        </metric>
      </store>
    </match>




    # Monitoring #

    # count number of incoming records per tag
    <filter **>
      @type prometheus
      <metric>
        name fluentd_input_status_num_records_total
        type counter
        desc The total number of incoming records
        <labels>
          tag ${tag}
          hostname ${hostname}
        </labels>
      </metric>
    </filter>

    <source>
      @type prometheus
      bind 0.0.0.0
      port 24231
      metrics_path /metrics
    </source>
    <source>
      @type prometheus_output_monitor
      interval 10
      <labels>
        hostname ${hostname}
      </labels>
    </source>
