apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: fluent-log-volume
          persistentVolumeClaim:
            claimName: fluent-pvc

      initContainers:
        - name: prepare-node-for-fluent
          image: busybox
          command:
            - sh
            - -c
            - chmod -R 0777 /var/log/fluent
          volumeMounts:
            - name: fluent-log-volume
              mountPath: /var/log/fluent
          resources:
            requests:
              memory: 32Mi
      containers:
        - name: fluentd
          image: london.alexswilliams.co.uk:5000/fluentd-custom:fluentd-v1.7.0-debian-1.0--20190827-2349
          resources:
            requests:
              memory: 65Mi
              cpu: 75m
            limits:
              memory: 80Mi
              cpu: 100m
          env:
            - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
              value: "0.9"
          ports:
            - containerPort: 5140
              protocol: UDP
              hostPort: 5140
              name: syslog-router
            - containerPort: 5141
              protocol: UDP
              hostPort: 5141
              name: syslog-ap
            - containerPort: 24231
              name: metrics

          volumeMounts:
            - mountPath: /fluentd/etc/fluent.conf
              name: fluentd-config
              subPath: fluent.conf
              readOnly: true
            - name: fluent-log-volume
              mountPath: /var/log/fluent/


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <system>
        log_level    debug
    </system>

    <source>
        @type udp
        port 5140
        message_length_limit 4096
        source_address_key      syslog_host
        <parse>
            @type regexp
            expression    /^\<(?<pri>[^>]+)\>(?<timestamp>(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) ([ ][1-9]|[1-2][0-9]|30|31) [0-2][0-9]:[0-5][0-9]:[0-5][0-9]) (?<hostname>[^ :]+):? (?<message>.*)$/
            time_key        timestamp
            time_format     %b %e %H:%M:%S
            localtime       true
            keep_time_key   true
            types           pri:integer
        </parse>
        tag from.draytek
    </source>

    # Monitoring #
    <source>
        @type prometheus
        bind 0.0.0.0
        port 24231
        metrics_path /metrics
    </source>
    <source>
        @type prometheus_output_monitor
        interval 10
        <labels>
            hostname ${hostname}
        </labels>
    </source>
    <filter **>
        @type prometheus
        <metric>
            name fluentd_input_status_num_records_total
            type counter
            desc The total number of incoming records
            <labels>
                tag ${tag}
                hostname ${hostname}
            </labels>
        </metric>
    </filter>


    # <150>Jun  5 02:28:45 88BL: Local User (MAC=B0-2A-43-48-A8-95): 192.168.1.32 DNS -> 8.8.8.8 inquire connectivitycheck.gstatic.com
    <filter from.draytek>
        @type           parser
        key_name        message
        reserve_data    true
        emit_invalid_record_to_error    false
        <parse>
            @type       regexp
            expression  /^Local User .MAC=(?<lu_mac>[^)]+).: (?<lu_source_ip>[0-9.]+) DNS -> (?<lu_dns_server>[0-9.]+) inquire (?<lu_dns_inquire_hostname>.*)$/
        </parse>
    </filter>

    # <150>Jun  5 02:28:33 88BL: Local User (MAC=78-4F-43-69-61-9B): 192.168.1.23:54381 -> 192.0.78.33:443 (TCP) close connection
    <filter from.draytek>
        @type           parser
        key_name        message
        reserve_data    true
        emit_invalid_record_to_error    false
        <parse>
            @type       regexp
            expression  /^Local User .MAC=(?<lu_mac>[^)]+).: (?<lu_source_ip>[0-9.]+):(?<lu_source_port>[0-9]+) -> (?<lu_dest_ip>[0-9.]+):(?<lu_dest_port>[0-9]+) \(TCP\).*$/
            types       lu_source_port:integer,lu_dest_port:integer
        </parse>
    </filter>

    # <150>Jun  5 02:28:38 88BL: Local User (MAC=00-1D-AA-3D-4F-86): 192.168.1.254 -> 8.8.8.8 (ICMP) Echo
    <filter from.draytek>
        @type           parser
        key_name        message
        reserve_data    true
        emit_invalid_record_to_error    false
        <parse>
            @type       regexp
            expression  /^Local User .MAC=(?<lu_mac>[^)]+).: (?<lu_source_ip>[0-9.]+) -> (?<lu_dest_ip>[0-9.]+) \(ICMP\) (?<lu_icmp_verb>.*)$/
        </parse>
    </filter>

    # <150>Jun  5 02:28:38 88BL: Local User: 8.8.8.8 -> 192.168.1.254 (ICMP) Echo Reply
    <filter from.draytek>
        @type           parser
        key_name        message
        reserve_data    true
        emit_invalid_record_to_error    false
        <parse>
            @type       regexp
            expression  /^Local User: (?<lu_source_ip>[0-9.]+) -> (?<lu_dest_ip>[0-9.]+) \(ICMP\) (?<lu_icmp_verb>.*)$/
        </parse>
    </filter>

    # <174>Jun  5 02:28:46 88BL: ADSL_Status:[Mode=17A States=SHOWTIME UpSpeed=5414000 DownSpeed=26016000 SNR=7 Atten=25 ]
    <filter from.draytek>
        @type           parser
        key_name        message
        reserve_data    true
        emit_invalid_record_to_error    false
        <parse>
            @type       regexp
            expression  /^ADSL_Status:\[Mode=(?<adsl_mode>[^ ]+) States=(?<adsl_states>[^ ]+) UpSpeed=(?<adsl_upspeed>[^ ]+) DownSpeed=(?<adsl_downspeed>[^ ]+) SNR=(?<adsl_snr>[^ ]+) Atten=(?<adsl_atten>[^ ]+) \]$/
            types       adsl_upspeed:integer,adsl_downspeed:integer,adsl_snr:integer,adsl_atten:integer
        </parse>
    </filter>


    <match **>
        @type copy

        <store>
            @type file
            path /var/log/fluent/all/
            time_slice_format %Y%m%d
            compress gzip
            append true
            <buffer>
                timekey_use_utc
            </buffer>
        </store>

        # Monitoring
        <store ignore_error>
        # count number of outgoing records per tag
        @type prometheus
        <metric>
          name fluentd_output_status_num_records_total
          type counter
          desc The total number of outgoing records
          <labels>
            tag ${tag}
            hostname ${hostname}
          </labels>
        </metric>
        </store>
    </match>
