apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      # tolerations:
      #   - key: node-role.kubernetes.io/master
      #     effect: NoSchedule

      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config

      containers:
      - name: fluentd
        image: fluent/fluentd:stable
        ports:
        - containerPort: 9800
          protocol: TCP
          hostPort: 9800
          name: fluent-test
        - containerPort: 5140
          protocol: TCP
          hostPort: 5140
          name: fluent-syslog-tcp
        - containerPort: 5140
          protocol: UDP
          hostPort: 5140
          name: fluent-syslog-udp

        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: fluentd-config
          subPath: fluent.conf
          readOnly: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type http
      @id test_source
      port 9800
    </source>
    <source>
      @type syslog
      port 5140
      protocol_type udp
      message_length_limit 4096
      tag from_syslog
    </source>
    <match **>
      @type stdout
      @id console_out
    </match>
