apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd

  template:

    metadata:
      labels:
        app: fluentd

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule

      volumes:
      - name: fluentd-config
        configMap:
          name: fluentd-config

      containers:
      - name: fluentd
        image: fluent/fluentd:stable
        ports:
        - containerPort: 5140
          protocol: UDP
          hostPort: 5140
          name: syslog-udp

        volumeMounts:
        - mountPath: /fluentd/etc/fluent.conf
          name: fluentd-config
          subPath: fluent.conf
          readOnly: true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type syslog
      port 5140
      protocol_type udp
      message_length_limit 4096
      message_format auto
      tag from_syslog
    </source>
    <filter **>
      @type stdout
      @id console_out
    </filter>
    <match from_syslog.**>
      @type elasticsearch
      logstash_format true
      <buffer>
        flush_interval 10s
      </buffer>
    </match>
