apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter

  template:

    metadata:
      labels:
        app: node-exporter

    spec:
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      priorityClassName: optional-metrics
      automountServiceAccountToken: false

      hostPID: true
      hostIPC: true
      hostNetwork: true

      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule

      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.0.0
          volumeMounts:
            - mountPath: /host/root
              name: root
              readOnly: true
            - mountPath: /host/sys
              name: sys
              readOnly: true
            - mountPath: /host/proc
              name: proc
              readOnly: true
          args:
            - --web.disable-exporter-metrics
            - --collector.filesystem.ignored-mount-points=^/(host/)?(root/)?(sys|proc|run|dev|host|etc|var/lib/lxcfs|var/lib/docker/.+|var/lib/kubelet/.+)($$|/)
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: true
            procMount: Unmasked
          resources:
            requests:
              memory: "6Mi"
              cpu: "6m"
            limits:
              memory: "16Mi"
              cpu: "15m"
          ports:
            - containerPort: 9100
              name: http
