# Limits and defaults per pod/container
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
spec:
  limits:
    - type: Pod
      min:
        memory: 16Mi
        cpu: 10m
      max:
        memory: 512Mi
        cpu: 1000m

    - type: Container
      defaultRequest:
        memory: 32Mi
        cpu: 20m
      default:  # default limit
        memory: 384Mi
        cpu: 150m
      min:
        memory: 16Mi
        cpu: 10m
      max:
        memory: 512Mi
        cpu: 1000m
