# Limits and defaults per pod/container
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
    - type: Pod
      min: # limit
        memory: 1Mi
        cpu: 1m
      max: # limit
        memory: 256Mi
        cpu: 250m

    - type: Container
      defaultRequest: # default request
        memory: 32Mi
        cpu: 5m
      default:  # default limit
        memory: 64Mi
        cpu: 25m
      min: # limit
        memory: 1Mi
        cpu: 1m
      max: # limit
        memory: 256Mi
        cpu: 250m
