# Limits and defaults per pod/container
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limit-range
  namespace: default
spec:
  limits:
    - type: Pod
      min:
        memory: 1Mi
        cpu: 10m
      max:
        memory: 256Mi
        cpu: 200m

    - type: Container
      defaultRequest:
        memory: 32Mi
        cpu: 20m
      default:  # default limit
        memory: 32Mi
        cpu: 20m
      min:
        memory: 1Mi
        cpu: 10m
      max:
        memory: 256Mi
        cpu: 200m
