# Hard limits across the namespace.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: default-resource-quota
  namespace: default
spec:
  hard:
    requests.memory: 1800Mi
    requests.cpu: 950m
    limits.memory: 1800Mi
    limits.cpu: 950m
