apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  labels:
    app: fluentd
spec:
  type: NodePort
  ports:
  - port: 9800
    name: fluent-test-external
    targetPort: fluent-test
    nodePort: 30000
  - port: 5140
    name: fluent-syslog-tcp-external
    targetPort: fluent-syslog-tcp
    protocol: TCP
    nodePort: 30001
  - port: 5140
    name: fluent-syslog-tcp-external
    targetPort: fluent-syslog-udp
    protocol: UDP
    nodePort: 30001
  selector:
    app: fluentd
