apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  labels:
    app: fluentd
spec:
  type: NodePort
  ports:
  - port: 9800
    name: fluent-test-external
    targetPort: fluent-test
    nodePort: 30000
  selector:
    app: fluentd
