apiVersion: v1
kind: Service
metadata:
  name: fluentd-service
  labels:
    app: fluentd
spec:
  type: NodePort
  ports:
  - port: 5140
    name: fluent-syslog-tcp-external
    targetPort: syslog-udp
    protocol: UDP
    nodePort: 30001
  selector:
    app: fluentd
