apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    name: grafana-http
    targetPort: http
  selector:
    app: grafana
