apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana
spec:
  type: ClusterIP
  ports:
  - port: 5601
    name: kibana-http
    targetPort: http
  selector:
    app: kibana
