apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
  - port: 5601
    name: kibana-http-external
    targetPort: http
    nodePort: 30002
  selector:
    app: kibana
