apiVersion: v1
kind: Service
metadata:
  name: node-exporter-service
spec:
  type: ClusterIP
  ports:
  - port: 9100
    name: node-exporter-http
    targetPort: http
  selector:
    app: node-exporter
