apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  type: ClusterIP
  ports:
  - port: 5000
    name: registry-port-external
    targetPort: registry-port
  selector:
    app: registry
