apiVersion: v1
kind: Service
metadata:
  name: artifactory-service
  labels:
    app: artifactory
spec:
  ports:
    - port: 8099
      name: frontend
  clusterIP: None
  selector:
    app: artifactory
