apiVersion: apps/v1
kind: Deployment
metadata:
  name: pptp-server
spec:
  selector:
    matchLabels:
      app: pptp-server

  template:

    metadata:
      labels:
        app: pptp-server

    spec:
      containers:
      - name: pptp-server
        image: pptp-server
        ports:
        - containerPort: 1723
          name: pptp-port
        volumeMounts:
        - mountPath: /etc/ppp/chap-secrets
          name: pptp-config
          subPath: chap-secrets
          readOnly: true
        - mountPath: /etc/pptpd.conf
          name: pptp-config
          subPath: pptpd.conf
          readOnly: true
        - mountPath: /etc/ppp/pptpd-options
          name: pptp-config
          subPath: pptpd-options
          readOnly: true

      volumes:
      - name: pptp-config
        configMap:
          name: pptp-config
          items:
          - key: chap-secrets
            path: ../../pptp-config/chap-secrets
          - key: pptpd.conf
            path: ../../pptp-config/pptpd-conf
          - key: pptpd-options
            path: ../../pptp-config/pptpd-options
