apiVersion: apps/v1
kind: Deployment
metadata:
  name: pptp-server
spec:
  selector:
    matchLabels:
      app: pptp-server

  replicas: 1
  strategy:
    type: Recreate

  template:

    metadata:
      labels:
        app: pptp-server

    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      priorityClassName: infrastructure

      volumes:
        - name: pptp-config
          configMap:
            name: pptp-config
        - name: pptp-chap-secrets
          secret:
            secretName: pptp-chap-secrets
            defaultMode: 0400

      containers:
        - name: pptp-server
          image: london.alexswilliams.co.uk:5000/pptp-server:alpine-3.11.3--20200127-0034
          imagePullPolicy: Always
          resources:
            requests:
              memory: "16Mi"
              cpu: "5m"
            limits:
              memory: "24Mi"
              cpu: "20m"
          ports:
            - containerPort: 1723
              name: pptp-port
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /etc/ppp/chap-secrets
              name: pptp-chap-secrets
              subPath: pptp-chap-secrets
              readOnly: true
            - mountPath: /etc/pptpd.conf
              name: pptp-config
              subPath: pptpd.conf
              readOnly: true
            - mountPath: /etc/ppp/pptpd-options
              name: pptp-config
              subPath: pptpd-options
              readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pptp-config
data:
  pptpd.conf: |
    option /etc/ppp/pptpd-options
    delegate
    remoteip 10.254.1.2-254
  pptpd-options: |
    10.254.1.1:
    name vpn.alexswilliams.co.uk

    refuse-pap
    refuse-chap
    refuse-mschap
    require-mschap-v2
    require-mppe-128

    # proxyarp
    nodefaultroute

    lock
    nologfd
    noipx
    mtu 1376
    mru 1376

    netmask 255.255.255.0
    ms-dns 8.8.8.8
    ms-dns 8.8.4.4
