---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      priorityClassName: optional-metrics
      volumes:
        - name: config
          configMap:
            name: telegraf-config
            defaultMode: 0444
      containers:
        - name: telegraf
          image: telegraf:1.13.0-alpine
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 9273
              name: http-metrics
          volumeMounts:
            - name: config
              mountPath: /etc/telegraf/telegraf.conf
              subPath: telegraf.conf
              readOnly: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
data:
  telegraf.conf: |
    [global_tags]

    [agent]
      interval = "30s"
      round_interval = true

      metric_batch_size = 1000
      metric_buffer_limit = 10000

      collection_jitter = "0s"
      flush_interval = "30s"
      flush_jitter = "0s"

      precision = ""

      debug = true
      quiet = false

      hostname = "k8s"
      ## If set to true, do no set the "host" tag in the telegraf agent.
      omit_hostname = false


    [[outputs.prometheus_client]]
        listen = ":9273"
        metric_version = 2
        path = "/metrics"
        expiration_interval = "240s"
        collectors_exclude = ["gocollector", "process"]
        export_timestamp = true
        string_as_label = false


    [[processors.regex]]
      [[processors.regex.fields]]
      key = "sysDescr"
      pattern = "^.*CPU Usage: *(\\d+)%.*$"
      replacement = "${1}"
      result_key = "cpuUsage"

      [[processors.regex.fields]]
      key = "sysDescr"
      pattern = "^.*Memory Usage: *(\\d+)%.*$"
      replacement = "${1}"
      result_key = "memoryUsage"


    [[processors.converter]]
      [processors.converter.fields]
        float = ["memoryUsage", "cpuUsage"]



    [[inputs.snmp]]
      agents = [ "10.254.1.10" ]
      timeout = "150s"
      retries = 3
      version = 2
      community = "public"
      max_repetitions = 10

      [[inputs.snmp.field]]
        name = "hostname"
        oid = "RFC1213-MIB::sysName.0"
        is_tag = true

      [[inputs.snmp.field]]
        name = "uptime"
        oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"


      [[inputs.snmp.field]]
        name = "sysDescr"
        oid = "SNMPv2-MIB::sysDescr.0"



      [[inputs.snmp.table]]
        name = "interface"
        inherit_tags = [ "hostname" ]
        oid = "IF-MIB::ifTable"

        # Interface tag - used to identify interface in metrics database
        [[inputs.snmp.table.field]]
          name = "ifDescr"
          oid = "IF-MIB::ifDescr"
          is_tag = true


      [[inputs.snmp.field]]
        name = "ipForwarding"
        oid = "IP-MIB::ipForwarding.0"

      [[inputs.snmp.field]]
        name = "ipDefaultTTL"
        oid = "IP-MIB::ipDefaultTTL.0"

      [[inputs.snmp.field]]
        name = "ipInReceives"
        oid = "IP-MIB::ipInReceives.0"

      [[inputs.snmp.field]]
        name = "ipInHdrErrors"
        oid = "IP-MIB::ipInHdrErrors.0"

      [[inputs.snmp.field]]
        name = "ipInAddrErrors"
        oid = "IP-MIB::ipInAddrErrors.0"

      [[inputs.snmp.field]]
        name = "ipForwDatagrams"
        oid = "IP-MIB::ipForwDatagrams.0"

      [[inputs.snmp.field]]
        name = "ipInUnknownProtos"
        oid = "IP-MIB::ipInUnknownProtos.0"

      [[inputs.snmp.field]]
        name = "ipInDiscards"
        oid = "IP-MIB::ipInDiscards.0"

      [[inputs.snmp.field]]
        name = "ipInDelivers"
        oid = "IP-MIB::ipInDelivers.0"

      [[inputs.snmp.field]]
        name = "ipOutRequests"
        oid = "IP-MIB::ipOutRequests.0"

      [[inputs.snmp.field]]
        name = "ipOutDiscards"
        oid = "IP-MIB::ipOutDiscards.0"

      [[inputs.snmp.field]]
        name = "ipOutNoRoutes"
        oid = "IP-MIB::ipOutNoRoutes.0"

      [[inputs.snmp.field]]
        name = "ipReasmTimeout"
        oid = "IP-MIB::ipReasmTimeout.0"

      [[inputs.snmp.field]]
        name = "ipReasmReqds"
        oid = "IP-MIB::ipReasmReqds.0"

      [[inputs.snmp.field]]
        name = "ipReasmOKs"
        oid = "IP-MIB::ipReasmOKs.0"

      [[inputs.snmp.field]]
        name = "ipReasmFails"
        oid = "IP-MIB::ipReasmFails.0"

      [[inputs.snmp.field]]
        name = "ipFragOKs"
        oid = "IP-MIB::ipFragOKs.0"

      [[inputs.snmp.field]]
        name = "ipFragFails"
        oid = "IP-MIB::ipFragFails.0"

      [[inputs.snmp.field]]
        name = "ipFragCreates"
        oid = "IP-MIB::ipFragCreates.0"

      [[inputs.snmp.field]]
        name = "ipRoutingDiscards"
        oid = "IP-MIB::ipRoutingDiscards.0"



      [[inputs.snmp.field]]
        name = "tcpRtoAlgorithm"
        oid = "TCP-MIB::tcpRtoAlgorithm.0"

      [[inputs.snmp.field]]
        name = "tcpRtoMin"
        oid = "TCP-MIB::tcpRtoMin.0"

      [[inputs.snmp.field]]
        name = "tcpRtoMax"
        oid = "TCP-MIB::tcpRtoMax.0"

      [[inputs.snmp.field]]
        name = "tcpMaxConn"
        oid = "TCP-MIB::tcpMaxConn.0"

      [[inputs.snmp.field]]
        name = "tcpActiveOpens"
        oid = "TCP-MIB::tcpActiveOpens.0"

      [[inputs.snmp.field]]
        name = "tcpPassiveOpens"
        oid = "TCP-MIB::tcpPassiveOpens.0"

      [[inputs.snmp.field]]
        name = "tcpAttemptFails"
        oid = "TCP-MIB::tcpAttemptFails.0"

      [[inputs.snmp.field]]
        name = "tcpEstabResets"
        oid = "TCP-MIB::tcpEstabResets.0"

      [[inputs.snmp.field]]
        name = "tcpCurrEstab"
        oid = "TCP-MIB::tcpCurrEstab.0"

      [[inputs.snmp.field]]
        name = "tcpInSegs"
        oid = "TCP-MIB::tcpInSegs.0"

      [[inputs.snmp.field]]
        name = "tcpOutSegs"
        oid = "TCP-MIB::tcpOutSegs.0"

      [[inputs.snmp.field]]
        name = "tcpRetransSegs"
        oid = "TCP-MIB::tcpRetransSegs.0"

      [[inputs.snmp.field]]
        name = "tcpInErrs"
        oid = "TCP-MIB::tcpInErrs.0"

      [[inputs.snmp.field]]
        name = "tcpOutRsts"
        oid = "TCP-MIB::tcpOutRsts.0"



      [[inputs.snmp.field]]
        name = "udpInDatagrams"
        oid = "UDP-MIB::udpInDatagrams.0"

      [[inputs.snmp.field]]
        name = "udpNoPorts"
        oid = "UDP-MIB::udpNoPorts.0"

      [[inputs.snmp.field]]
        name = "udpInErrors"
        oid = "UDP-MIB::udpInErrors.0"

      [[inputs.snmp.field]]
        name = "udpOutDatagrams"
        oid = "UDP-MIB::udpOutDatagrams.0"




      [[inputs.snmp.field]]
      # unit: tenth dBm
        name = "adslAturCurrSnrMgn"
        oid = "SNMPv2-SMI::transmission.94.1.1.3.1.4.4"

      [[inputs.snmp.field]]
      # unit: tenth dBm
        name = "adslAturCurrAtn"
        oid = "SNMPv2-SMI::transmission.94.1.1.3.1.5.4"

      [[inputs.snmp.field]]
      # unit: tenth dBm
        name = "adslAturCurrOutputPwr"
        oid = "SNMPv2-SMI::transmission.94.1.1.3.1.7.4"

      [[inputs.snmp.field]]
      # unit: bps
        name = "adslAturCurrAttainableRate"
        oid = "SNMPv2-SMI::transmission.94.1.1.3.1.8.4"

      [[inputs.snmp.field]]
      # unit: ms
        name = "adslAtucChanInterleaveDelay"
        oid = "SNMPv2-SMI::transmission.94.1.1.4.1.1.4"

      [[inputs.snmp.field]]
      # unit: bps
        name = "adslAtucChanCurrTxRate"
        oid = "SNMPv2-SMI::transmission.94.1.1.4.1.1.4"

      [[inputs.snmp.field]]
      # unit: bps
        name = "adslAtucChanPrevTxRate"
        oid = "SNMPv2-SMI::transmission.94.1.1.4.1.3.4"

      [[inputs.snmp.field]]
      # unit: byte
        name = "adslAtucChanCrcBlockLength"
        oid = "SNMPv2-SMI::transmission.94.1.1.4.1.4.4"

      [[inputs.snmp.field]]
      # unit: ms
        name = "adslAturChanInterleaveDelay"
        oid = "SNMPv2-SMI::transmission.94.1.1.5.1.1.4"

      [[inputs.snmp.field]]
      # unit: bps
        name = "adslAturChanCurrTxRate"
        oid = "SNMPv2-SMI::transmission.94.1.1.5.1.2.4"

      [[inputs.snmp.field]]
      # unit: bps 
        name = "adslAturChanPrevTxRate"
        oid = "SNMPv2-SMI::transmission.94.1.1.5.1.3.4"

      [[inputs.snmp.field]]
      # unit: byte
        name = "adslAturChanCrcBlockLength"
        oid = "SNMPv2-SMI::transmission.94.1.1.5.1.4.4"

