apiVersion: apps/v1
kind: Deployment
metadata:
  name: washing-tweeter
spec:
  selector:
    matchLabels:
      app: washing-tweeter
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: washing-tweeter
    spec:
      containers:
        - name: washing-tweeter
          image: london.alexswilliams.co.uk:5000/washing-tweeter:node-10-alpine--20191116-2135
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
            limits:
              memory: "32Mi"
              cpu: "20m"
          env:
            - name: SERVER_PORT
              value: "80"
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: consumer-key
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: consumer-secret
            - name: TWITTER_ACCESS_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: access-token-key
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: access-token-secret
          ports:
            - containerPort: 80
              name: http
