apiVersion: apps/v1
kind: Deployment
metadata:
  name: washing-tweeter
spec:
  selector:
    matchLabels:
      app: washing-tweeter
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: washing-tweeter
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 5
      priorityClassName: alerting
      containers:
        - name: washing-tweeter
          image: london.alexswilliams.co.uk:5000/washing-tweeter:node-13.7.0-alpine--20200127-0025
          livenessProbe:
              httpGet:
                path: "/liveness"
                port: http
              initialDelaySeconds: 10
              failureThreshold: 2
              periodSeconds: 10
          readinessProbe:
              httpGet:
                path: "/readiness"
                port: http
              initialDelaySeconds: 10
              failureThreshold: 1
              periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "2m"
            limits:
              memory: "96Mi"
              cpu: "80m"
          env:
            - name: NODE_OPTIONS
              # https://developer.ibm.com/technologies/node-js/articles/nodejs-memory-management-in-container-environments#summary-and-recommendations
              value: "--max-old-space-size=54"
            - name: SERVER_PORT
              value: "8080"
            - name: PROMETHEUS_URL
              value: "http://prometheus-service:9090"
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: consumer-key
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: consumer-secret
            - name: TWITTER_ACCESS_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: access-token-key
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: washing-tweeter-secrets
                  key: access-token-secret
          ports:
            - containerPort: 8080
              name: http
