apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
spec:
  serviceName: prometheus-service
  selector:
    matchLabels:
      app: prometheus

  updateStrategy:
    type: RollingUpdate
  replicas: 1

  template:
    metadata:
      labels:
        app: prometheus

    spec:
      terminationGracePeriodSeconds: 60

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: config
          configMap:
            name: prometheus-config
            defaultMode: 0444

      initContainers:
        - name: prepare-volume-for-prometheus
          image: busybox
          command:
            - sh
            - -c
            - chmod -R 0777 /prometheus
          volumeMounts:
            - name: data
              mountPath: /prometheus
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 10m
      containers:
        - name: prometheus
          image: prom/prometheus:v2.12.0
          resources:
            requests:
              memory: 96Mi
              cpu: 70m
            limits:
              memory: 96Mi
              cpu: 70m
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
              readOnly: true
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --web.external-url=/prometheus/
            - --web.route-prefix=/
            - --storage.tsdb.path=/prometheus
            - --storage.tsdb.retention.time=1y
            - --storage.tsdb.retention.size=4GB
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s
      scrape_timeout:      10s
      evaluation_interval: 30s

    scrape_configs:
      - job_name: node-exporter-vps
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets:
              - node-exporter-service:9100

      - job_name: fluentd
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets:
              - fluentd-service:24231

      - job_name: 88bl-pi-node-exporter
        scrape_interval: 10s
        metrics_path: /metrics
        static_configs:
          - targets:
              - 2.24.116.170:30001

      - job_name: 88bl-pi-push-gateway
        scrape_interval: 5s
        scrape_timeout: 5s
        metrics_path: /metrics
        static_configs:
          - targets:
              - 2.24.116.170:20002

      - job_name: alex-minecraft-desktop
        scrape_interval: 10s
        scrape_timeout: 10s
        metrics_path: /metrics
        static_configs:
          - targets:
              - 2.24.116.170:30004

      - job_name: 88bl-router-telegraf
        scrape_interval: 10s
        scrape_timeout: 10s
        metrics_path: /metrics
        static_configs:
          - targets:
              - 2.24.116.170:30005
