apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: backups
value: 1000
globalDefault: false
preemptionPolicy: Never
description: "Schedules first, but won't run if the cluster is full"
